const data = {
  products: [
    {
      name: "H&M Relaxed Fit T-shirt",
      slug: "hm-relaxed-tshirt",
      category: "Shirts",
      image: "../images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "H&M",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      name: "Lacoste Men's Pima T-Shirt",
      slug: "lacoste-men-s-crew-neck-pima-cotton-jersey-t-shirt",
      category: "Shirts",
      image: "../images/p2.jpg",
      price: 200,
      countInStock: 5,
      brand: "Lacoste",
      rating: 5,
      numReviews: 5,
      description: "Pima Cotton jersey",
    },
    {
      name: "DeFacto Cotton T-Shirt",
      slug: "defacto-slim-fit-ribana-cotton-athlete",
      category: "Shirts",
      image: "../images/p3.jpg",
      price: 50,
      countInStock: 8,
      brand: "DeFacto",
      rating: 3.5,
      numReviews: 7,
      description: "DeFacto Top that gives you comfort and flexibility to move",
    },
    {
      name: "H&M Regular Tapered Jeans",
      slug: "hm-regular-tapered-jeans-blue",
      category: "Pants",
      image: "../images/p4.jpg",
      price: 100,
      countInStock: 10,
      brand: "H&M",
      rating: 4,
      numReviews: 3,
      description: "5-pocket jeans in washed, stretch cotton denim with a regular waist, zip fly and button and gently tapered legs",
    },
    {
      name: "H&M Regular Fit Sweatpants",
      slug: "hm-regular-fit-sweatpants",
      category: "Pants",
      image: "../images/p5.jpg",
      price: 69,
      countInStock: 4,
      brand: "H&M",
      rating: 2,
      numReviews: 3,
      description: "Sweatpants in lightweight cotton sweatshirt fabric with covered elastication",
    },
    {
      name: "DeFacto Regular Fit Cargo",
      slug: "defacto-regular-fit-cargo-pocket-detail-woven-trousers",
      category: "Pants",
      image: "../images/p6.jpg",
      price: 144,
      countInStock: 0,
      brand: "DeFacto",
      rating: 1,
      numReviews: 1,
      description: "The DeFacto trousers which provide a stylish look which is both trendy and comfortable.",
    },
  ],
};

export default data;
